INSERT INTO mesas (numero, zona, capacidad, estado, zona_orden) VALUES
  ('Mesa 08', 'Salón Principal', 4, 'Libre', 11),
  ('Mesa 09', 'Salón Principal', 4, 'Libre', 12),
  ('Mesa 10', 'Salón Principal', 2, 'Libre', 13),
  ('Mesa 11', 'Salón Principal', 6, 'Libre', 14),
  ('Mesa 12', 'Salón Principal', 4, 'Libre', 15),
  ('Mesa 13 (Terraza)', 'Terraza', 4, 'Libre', 16),
  ('Mesa 14 (Terraza)', 'Terraza', 4, 'Libre', 17),
  ('Mesa 15 (Terraza)', 'Terraza', 2, 'Libre', 18),
  ('Mesa 16 (Terraza)', 'Terraza', 6, 'Libre', 19),
  ('Mesa 17 (Terraza)', 'Terraza', 4, 'Libre', 20),
  ('Barra 03', 'Barra', 1, 'Libre', 21),
  ('Barra 04', 'Barra', 1, 'Libre', 22),
  ('Barra 05', 'Barra', 2, 'Libre', 23),
  ('Barra 06', 'Barra', 2, 'Libre', 24),
  ('Mesa VIP 02', 'VIP', 8, 'Libre', 25),
  ('Mesa VIP 03', 'VIP', 6, 'Libre', 26),
  ('Mesa 18', 'Salón Principal', 4, 'Libre', 27),
  ('Mesa 19', 'Salón Principal', 4, 'Libre', 28),
  ('Mesa 20 (Terraza)', 'Terraza', 4, 'Libre', 29),
  ('Barra 07', 'Barra', 1, 'Libre', 30);
